# Generated by Django 4.0.5 on 2022-06-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='quiz.grade'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_categorys', to='quiz.subcategory'),
        ),
    ]
